name: Deploy

on:
  push:
    branches: ["main"]
    paths: site/**
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enter folder
        run: |
         zip -r site.zip ./site
      - name: 
        uses: IsaacShelton/update-existing-release@v1.3.5
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          release: "Rolling release"
          tag: "rolling"
          message: "rolling site release"
          body: "Rolling site release"
          files: >
            site.zip
