name: Deploy site

on:
    push:
        branches: ["main"]
        paths-ignore:
          - "*.md"
          - ".**"
          - "*LICENSE*"
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency: 
    group: "pages"
    cancel-in-progress: false

jobs:
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on : ubuntu-latest
        steps:
          - name: Checkout the repo
            uses: actions/checkout@v7
            with:
                submodules: true
          - name: Remove useless files
            run: |
                rm README.md
                rm LICENSE
                rm web/stare-at-burger/README.md
                rm web/stare-at-burger/LICENSE
                rm web/font-size-tester/README.md
                rm web/font-size-tester/LICENSE
          - name: Configure site
            uses: actions/configure-pages@v6
          - name: Upload site artifact
            uses: actions/upload-pages-artifact@v5
            with:
                path: "."
          - name: Deploy site
            id: deployment
            uses: actions/deploy-pages@v5
