name: Deploy

on:
  push:
    branches: ["main"]
    paths: site/**

permissions:
  contents: read
  id-token: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enter folder
        run: |
        #zip -r site.zip ./site
      - name: 
        uses: IsaacShelton/update-existing-release@v1.3.5
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          release: "Development release"
          tag: "develop"
          message: "development release"
          body: "Release from the develop branch, also since I'm too lazy to redownload the site zip."
          files: >
            site.zip